apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ingress-nginx-public
  description: Internet facing loadbalancer
  annotations:
    argocd/app-name: ingress-nginx-public
    grafana/overview-dashboard: "https://grafana.jppol.click/goto/Hw7n7PzHR?orgId=1"
    grafana/dashboard-selector: nginx
    backstage.io/kubernetes-namespace: ingress-nginx
    backstage.io/kubernetes-label-selector: "app.kubernetes.io/component=controller"
    prometheus.io/rule: sum by (ingress) (nginx_ingress_controller_requests{ingress!=""}), nginx_ingress_controller_nginx_process_resident_memory_bytes
    kubecost.com/deployment-name: homepage
  links:
    - url: https://argocd.jppol.click
      title: ArgoCD
      icon: dashboard
    - url: https://grafana.jppol.click/goto/JCdVqlzHg?orgId=1
      title: Grafana loki Access log explorer
      icon: grafana
spec:
  type: service
  owner: backstage-idp-admins
  lifecycle: production
