apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ingress-nginx-public
  description: Internet facing loadbalancer
  annotations:
    argocd/app-name: ingress-nginx-public
    grafana/overview-dashboard: 'https://grafana.jppol.click/goto/Hw7n7PzHR?orgId=1'
    grafana/dashboard-selector: nginx
#    prometheus.io/rule: memUsage|component,node_memory_active_bytes|instance,sum by (instance) (node_cpu_seconds_total)
    prometheus.io/rule: round(sum(irate(nginx_ingress_controller_requests{controller_pod=~".*",controller_class=~".*",controller_namespace=~".*",exported_namespace=~".*",ingress=~".*"}[2m])) by (ingress), 0.001)
  links:
    - url: https://argocd.jppol.click
      title: ArgoCD
      icon: dashboard
spec:
  type: service
  owner: guests
  lifecycle: production
