apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: kn-demo-1
  description: An example of a Backstage application.
  annotations:
    argocd/app-name: argocd
  links:
    - url: https://argocd.jppol.click
      title: ArgoCD
      icon: dashboard
  # Example for optional annotations
  # annotations:
  #   github.com/project-slug: backstage/backstage
  #   backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: kasper.kn.nielsen@jppol.dk
  lifecycle: production
