apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ingress-nginx-public
  description: Internet facing loadbalancer
  annotations:
    argocd/app-name: ingress-nginx-public
    grafana/overview-dashboard: "https://grafana.jppol.click/goto/Hw7n7PzHR?orgId=1"
    grafana/dashboard-selector: nginx
    prometheus.io/rule: sum by (ingress) (nginx_ingress_controller_requests)
  links:
    - url: https://argocd.jppol.click
      title: ArgoCD
      icon: dashboard
spec:
  type: service
  owner: guests
  lifecycle: production
