apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ingress-nginx-public
  description: Internet facing loadbalancer
  annotations:
    argocd/app-name: ingress-nginx-public
    grafana/overview-dashboard: 'https://grafana.jppol.click/d/nginx/nginx-ingress-controller?orgId=1&refresh=5s'
  links:
    - url: https://argocd.jppol.click
      title: ArgoCD
      icon: dashboard
spec:
  type: Loadbalancer
  owner: kasper.kn.nielsen@jppol.dk
  lifecycle: production
